<?php include 'incs/header.php'; ?>
<?php include 'incs/popup.php'; ?>
<?php include 'incs/banners/banner-onlytitle.php'; ?>
<?php include 'incs/pricing-table.php'; ?>
<?php include 'incs/pricing-table.php'; ?>
<?php include 'incs/bgwithicons-online-trading.php'; ?>
<?php include 'incs/three-column-icon-text.php'; ?>
<?php include 'incs/trade-smarter2.php'; ?>
<?php include 'incs/testimonials-and-ratings.php'; ?>
<?php include 'incs/start-trading-today.php'; ?>
<?php include 'incs/footer.php'; ?>