<?php include 'incs/header.php'; ?>
<?php include 'incs/popup.php'; ?>
<?php include 'incs/banners/banner1.php'; ?>
<?php include 'incs/statistics.php'; ?>
<?php include 'incs/how-it-works.php'; ?>
<?php include 'incs/bgwithicons-home.php'; ?>
<?php include 'incs/trade-smarter.php'; ?>
<?php include 'incs/testimonials-and-ratings.php'; ?>
<?php include 'incs/trade-smarter2.php'; ?>
<?php include 'incs/team.php'; ?>
<?php include 'incs/our-partners.php'; ?>
<?php include 'incs/triple-column-news.php'; ?>
<?php include 'incs/start-trading-today.php'; ?>
<?php include 'incs/footer.php'; ?>