<?php include 'incs/header.php'; ?>
<?php include 'incs/popup.php'; ?>
<?php include 'incs/banners/banner2.php'; ?>
<?php include 'incs/how-it-works-online-trading.php'; ?>
<?php include 'incs/pricing-table.php'; ?>
<?php include 'incs/bgwithicons-online-trading.php'; ?>
<?php include 'incs/three-column-icon-text.php'; ?>
<?php include 'incs/faq-dualcolumn.php'; ?>
<?php include 'incs/how-it-works.php'; ?>
<?php include 'incs/trade-smarter.php'; ?>
<?php include 'incs/team.php'; ?>
<?php include 'incs/start-trading-today-greenbg.php'; ?>
<?php include 'incs/faq-full-lightbg.php'; ?>
<?php include 'incs/faq-full.php'; ?>
<?php include 'incs/footer.php'; ?>