<?php include 'incs/header.php'; ?>
<?php include 'incs/popup.php'; ?>
<?php include 'incs/banners/banner3.php'; ?>
<?php include 'incs/how-it-works.php'; ?>
<?php include 'incs/pricing-table.php'; ?>
<?php include 'incs/bgwithicons-online-trading.php'; ?>
<?php include 'incs/three-column-icon-text.php'; ?>
<?php include 'incs/trade-smarter2.php'; ?>
<?php include 'incs/three-rows-icons-text.php'; ?>
<?php include 'incs/start-trading-today-greenbg.php'; ?>
<?php include 'incs/common-questions.php'; ?>
<?php include 'incs/footer.php'; ?>